### ISSUE TITLE
more naming

### ISSUE THREAD

**Issue by ruslo** [ruslo/0#2]
* naming `IT_IS_HEADER_GUARD_`, `_macro_internal_variable`, `__USED_FOR_STRING_COMPARE__`

**Comment by pretyman** [comment]
Can you confirm that the single `_` is used in macros internal variables only and nowhere else? Thanks

**Comment by ruslo** [comment]
> Can you confirm that the single _ is used in macros internal variables only and nowhere else?

Also in headers, updated: https://github.com/ruslo/0/wiki/CMake#naming

**Comment by ruslo** [comment]
> `IT_IS_HEADER_GUARD_`

Updated: https://github.com/ruslo/0/wiki/CMake#naming

> `__USED_FOR_STRING_COMPARE__`

Not needed, since `string(COMPARE EQUAL ...` can be used
